# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 15:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('URL', models.URLField(null=True)),
                ('file_type', models.CharField(max_length=5)),
                ('publication_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.ContentItem')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('personal_info', models.TextField()),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('expertise', models.TextField()),
                ('contact_phone', models.IntegerField(null=True)),
                ('contact_skype', models.URLField(null=True)),
                ('contact_facebook', models.URLField(null=True)),
                ('contact_linkedin', models.URLField(null=True)),
                ('user_photo', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'j2k', 'gif', 'ps', 'jpe', 'rgba', 'pgm', 'gbr', 'grib', 'jpc', 'jpx', 'fli', 'mpg', 'msp', 'jpf', 'mpeg', 'pcx', 'ras', 'rgb', 'icns', 'sgi', 'jpg', 'cur', 'jp2', 'psd', 'tif', 'jpeg', 'h5', 'jfif', 'pcd', 'ico', 'eps', 'bw', 'ppm', 'bufr', 'iim', 'png', 'hdf', 'dcx', 'bmp', 'im', 'fpx', 'tiff', 'fit', 'mpo', 'xbm', 'emf', 'j2c', 'wmf', 'fits', 'xpm', 'palm', 'flc', 'tga', 'pbm', 'mic'])])),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.User'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.User'),
        ),
        migrations.AddField(
            model_name='contenthashtag',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.ContentItem'),
        ),
        migrations.AddField(
            model_name='contenthashtag',
            name='hashtag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.Hashtag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.ContentItem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.User'),
        ),
    ]
