# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('content_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('URL', models.URLField()),
                ('file_type', models.CharField(max_length=5)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.ContentItem')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hashtag_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('personal_info', models.TextField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('expertise', models.TextField()),
                ('contact_phone', models.IntegerField()),
                ('contact_skype', models.URLField()),
                ('contact_facebook', models.URLField()),
                ('contact_linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('picture_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('URL', models.URLField()),
                ('user_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.UserPicture'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.User'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.User'),
        ),
        migrations.AddField(
            model_name='contenthashtag',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.ContentItem'),
        ),
        migrations.AddField(
            model_name='contenthashtag',
            name='hashtag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.Hashtag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.ContentItem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.User'),
        ),
    ]
