# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='URL',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image',
            field=models.ImageField(default='null', upload_to='image_board/posts/'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='uploaded_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='description',
            field=models.CharField(default='no description', max_length=400),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
