# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
