# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0002_auto_20170615_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_id',
            new_name='contentItem',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
