# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0002_auto_20170527_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_photo',
        ),
    ]
