# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0006_auto_20170627_2054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='upvote',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_board.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
    ]
