# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 09:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0006_auto_20170528_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpc', 'dcx', 'mpg', 'j2c', 'fits', 'tiff', 'psd', 'jpx', 'xpm', 'jp2', 'jpe', 'fpx', 'fit', 'png', 'ps', 'rgba', 'wmf', 'mic', 'pdf', 'pgm', 'flc', 'tga', 'jpg', 'ppm', 'emf', 'msp', 'mpo', 'ras', 'ico', 'bw', 'j2k', 'im', 'icns', 'bmp', 'gbr', 'hdf', 'grib', 'h5', 'tif', 'cur', 'eps', 'xbm', 'pcx', 'fli', 'sgi', 'pbm', 'bufr', 'iim', 'jpeg', 'jpf', 'palm', 'gif', 'mpeg', 'pcd', 'jfif', 'rgb'])]),
        ),
    ]
