# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 09:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0007_auto_20170528_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'jpeg', 'tga', 'gif', 'jp2', 'j2k', 'pcx', 'ras', 'flc', 'psd', 'tiff', 'mic', 'jpf', 'xbm', 'mpg', 'ppm', 'pdf', 'dcx', 'pbm', 'jpg', 'palm', 'eps', 'emf', 'sgi', 'iim', 'j2c', 'icns', 'tif', 'jpc', 'im', 'jpx', 'rgba', 'xpm', 'pgm', 'mpo', 'fits', 'pcd', 'mpeg', 'wmf', 'bufr', 'grib', 'png', 'gbr', 'fit', 'cur', 'msp', 'hdf', 'fpx', 'ico', 'rgb', 'jpe', 'fli', 'bw', 'h5', 'jfif', 'ps'])]),
        ),
    ]
