# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0007_auto_20170630_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(default='/static/img/anon.png', upload_to='../media/img'),
        ),
    ]
