# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0008_auto_20170708_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='points',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='points_weighted',
            field=models.IntegerField(default=1000),
        ),
    ]
