# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 09:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0008_auto_20170528_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['j2c', 'iim', 'rgba', 'im', 'wmf', 'mpeg', 'palm', 'icns', 'jpeg', 'eps', 'ico', 'pbm', 'tga', 'ppm', 'bmp', 'jpe', 'j2k', 'grib', 'pdf', 'jpx', 'msp', 'jpf', 'jpg', 'jfif', 'mpg', 'gbr', 'emf', 'ras', 'h5', 'xpm', 'flc', 'fli', 'pgm', 'jpc', 'fits', 'hdf', 'xbm', 'mic', 'fpx', 'png', 'psd', 'ps', 'rgb', 'bufr', 'sgi', 'fit', 'bw', 'tiff', 'cur', 'jp2', 'gif', 'dcx', 'tif', 'mpo', 'pcd', 'pcx'])]),
        ),
    ]
