# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 09:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0009_auto_20170528_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sgi', 'tiff', 'cur', 'mpeg', 'bufr', 'rgb', 'ico', 'palm', 'eps', 'j2k', 'jfif', 'jpx', 'emf', 'xpm', 'tif', 'fpx', 'pcx', 'j2c', 'ppm', 'jpf', 'fli', 'psd', 'mpg', 'icns', 'dcx', 'ps', 'pdf', 'jpeg', 'fits', 'msp', 'flc', 'pcd', 'grib', 'fit', 'im', 'pgm', 'tga', 'mpo', 'png', 'iim', 'xbm', 'wmf', 'bmp', 'gbr', 'ras', 'jpg', 'bw', 'rgba', 'jpe', 'jpc', 'gif', 'jp2', 'mic', 'h5', 'pbm', 'hdf'])]),
        ),
    ]
