# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0011_auto_20170528_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sgi', 'bufr', 'icns', 'psd', 'h5', 'tga', 'fpx', 'fits', 'eps', 'jfif', 'bw', 'jpf', 'jpc', 'pbm', 'pgm', 'cur', 'gif', 'jpx', 'emf', 'jpg', 'ras', 'pdf', 'mpo', 'j2k', 'xpm', 'mpg', 'wmf', 'mic', 'bmp', 'iim', 'ps', 'xbm', 'j2c', 'msp', 'rgba', 'im', 'tiff', 'png', 'fit', 'dcx', 'fli', 'jp2', 'pcx', 'tif', 'jpeg', 'gbr', 'mpeg', 'ico', 'rgb', 'flc', 'grib', 'palm', 'ppm', 'hdf', 'jpe', 'pcd'])]),
        ),
    ]
