# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0012_auto_20170528_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['j2k', 'mpg', 'jp2', 'pbm', 'tif', 'png', 'pdf', 'fits', 'ppm', 'tga', 'jfif', 'mpo', 'mic', 'xbm', 'ico', 'emf', 'fpx', 'grib', 'sgi', 'rgb', 'ras', 'psd', 'j2c', 'rgba', 'mpeg', 'icns', 'msp', 'xpm', 'tiff', 'palm', 'jpx', 'jpe', 'pcx', 'pgm', 'jpg', 'iim', 'jpc', 'cur', 'bw', 'h5', 'fit', 'dcx', 'gif', 'jpeg', 'bufr', 'im', 'eps', 'jpf', 'hdf', 'ps', 'flc', 'gbr', 'bmp', 'pcd', 'fli', 'wmf'])]),
        ),
    ]
