# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_board', '0016_auto_20170528_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bufr', 'dcx', 'emf', 'eps', 'pdf', 'jfif', 'pcd', 'rgba', 'tiff', 'iim', 'palm', 'pbm', 'bmp', 'grib', 'jpg', 'jpx', 'xpm', 'ps', 'tif', 'rgb', 'mpg', 'flc', 'j2c', 'pgm', 'mic', 'fli', 'sgi', 'j2k', 'pcx', 'ico', 'fit', 'xbm', 'jpf', 'jpe', 'tga', 'psd', 'im', 'png', 'fits', 'h5', 'jpeg', 'cur', 'msp', 'wmf', 'fpx', 'bw', 'ras', 'mpo', 'jpc', 'icns', 'jp2', 'hdf', 'gif', 'gbr', 'ppm', 'mpeg'])]),
        ),
    ]
